# The name of your automated workflow
name: Build Flet macOS App

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on - THIS IS THE KEY PART
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Sets up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installs the necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          pip install pyinstaller

      # 4. Runs the Flet pack command to build the .app file
      - name: Build the macOS app
        run: flet pack Entry.py --onefile --name "ALA-Chatbot"

      # 5. Uploads the final .app file so you can download it
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/MyCoolApp.app
